services:
  - type: web
    name: smart-cart-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production