services:
  - type: web
    name: smart-cart-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://smart-cart-li2n.onrender.com
      - key: VITE_APP_NAME
        value: Smart Cart

  - type: web
    name: smart-cart-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        value: your_mongodb_connection_string_here
      - key: JWT_SECRET
        value: your_jwt_secret_here