services:
  - type: web
    name: smart-cart-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://yashasvig_db_user:zf21c8Akklv701Wb@smartcart.5nnr9do.mongodb.net/
      - key: JWT_SECRET
        value: SmartCart2026SecureSecretWithRandomCharacters12345
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080